WIP: Issue19 upgrade to angular6
unosquare/tubular2 pull request #20
Opened 2018-05-16 22:57 UTC by Israel-94

2018-05-17 13:35 UTC, geoperez commented
Instead of using a HttpOptions, try to create an interceptor to receive the request before to send (https://angular.io/guide/http#intercepting-requests-and-responses)

@kadosh what do you think??

2018-05-17 13:40 UTC, kadosh commented
The interceptor is the way to go in this case. You can also take a look at TB1 where an interceptor is already in place.

2018-05-17 13:41 UTC, geoperez commented
Go team go

On Thu, May 17, 2018, 8:40 AM Alejandro Ocampo <notifications@github.com>
wrote:

> The interceptor is the way to go in this case. You can also take a look at
> TB1 where an interceptor is already in place.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/unosquare/tubular2/pull/20#issuecomment-389869791>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABsYsOq7congZvv2mzP_9FsBWMtgwFq6ks5tzX3MgaJpZM4UCKf4>
> .
>

2018-05-18 20:08 UTC, geoperez requested changes

2018-05-18 20:08 UTC, geoperez commented on projects/tubular-lib/src/lib/interceptors/interceptor.ts
> +export class AuthInterceptor implements HttpInterceptor {
Rename the file to match the class name.

2018-05-18 20:57 UTC, geoperez approved these changes

2018-05-18 20:57 UTC, merged