Issue29 replacing momentjs for date-fns
unosquare/tubular2 pull request #30
Opened 2018-08-15 18:53 UTC by Serk352

The momentjs library has been replaced by the library date-fns.

closses #29

2018-08-15 19:03 UTC, geoperez requested changes

2018-08-15 19:03 UTC, geoperez commented on projects/tubular2/src/lib/grid/grid.ts
> +            console.log(` was key ${data[key]}  was name ${data[column.Name]}`);
Remove

2018-08-15 19:03 UTC, geoperez commented on projects/tubular2/src/lib/grid/grid.ts
> +                obj[column.Name] = format(obj[column.Name], 'MMMM Do YYYY, h:mm:ss a');
You need to transform to UTC here

2018-08-15 22:57 UTC, Serk352 commented
UTC time applied:

before:
![without_utc](https://user-images.githubusercontent.com/25519413/44177637-6a227280-a0b4-11e8-9f15-5992d30d8678.PNG)

After:
![utc time](https://user-images.githubusercontent.com/25519413/44177636-6a227280-a0b4-11e8-9860-660edb1ed30d.PNG)

2018-08-16 19:24 UTC, geoperez approved these changes

2018-08-16 19:24 UTC, merged